services:
  - type: web
    name: gurugram-traffic-app
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server.api:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TOMTOM_API_KEY
        sync: false
